### PR TITLE
nft/basic fix for ipfs and contract

### LINKED ISSUE #9: Fixing NFT basic Vue IPFS issue template
A change in the API of IPFS led to an error: 
```Error uploading file to IPFS:  HTTPError: project id required
for uploading to IPFS
7:15
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'tokens')
```
Therefor, @drewstaylor and I decided to start moving to an `on-chain metadata` template and remove the IPFS upload and make this Dapp work again until later creation of the `NFT on-chain metadata Dapp`

### PR DESCRIPTION
**Pull request by gachouchani1999**
- Upload NFT to Constantine code ID: 162
- Remove IPFS upload from App.vue
- Testing works for nft basic
- Closes #9

### CODE REVIEW

File: vuejs/nft-basic/src/App.vue [hunk 1]
```diff
@@ -214,10 +214,9 @@ import axios from 'axios';
 import ipfsClient from './ipfs';
```
Comment (aelesbao) [inline vuejs/nft-basic/src/App.vue]: Shouldn't we remove the `ipfsClient` too?

Comment (gachouchani1999) [reply vuejs/nft-basic/src/App.vue]: Removed all instances of IPFS from code

**Review by aelesbao — APPROVED** [review]
